name: Backend Lint

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21

    - name: Install Dependencies
      run: |
        cd backend
        npm ci

    - name: Run Lint
      run: |
        cd backend
        npm run lint
    
    - name: Run Prettier Check
      run: |
        cd backend
        npx prettier --check .


